name: CI
on:
  push:
    tags: [v*.*.*]
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Biome
        run: pnpm biome ci .
      - name: Build app
        run: pnpm build
